#!/usr/bin/env python3
##Generate Kibana Reports (from any environment on the fly) in few seconds with the help of shell scripting and Curl Commands##

import os
import stat
import sys
import subprocess as sp
import time
import re

username1 = input("Username Please")
Password1 = input("Password Please")
env1 = input("Pls type the environment name :\n")
var1 = input("From date")
var2 = input("To date")
fh1 = open("C:\\KibanaReports\\kibana3.txt", "r")
fh2 = open("C:\\KibanaReports\\kibanaa.sh", "w")
time.sleep(8)
s = fh1.readlines()
c = 1
for i in s:
    # print(i)
    p = '(2021-\d*-\d+[A-Z]\d*:\d*:\d*.\d*[A-Z])'
    username = 'username'
    password = 'Password'
    env2 = 'tenant'
    u = re.findall(username,i)
    p1 = re.findall(password, i)
    env3 = re.findall(env2, i)
    a = re.findall(p, i)
    # print(a[0])
    i1 = i.replace('tenant',env1).replace(a[0], var1).replace(a[1], var2).replace(u[0],username1).replace(p1[0],Password1)
    fh2.write(i1)
    c += 1
fh2.close()
a1 = "C:\\KibanaReports\\kibanaa.sh"
a = sp.call(['sh', 'C:/KibanaReports/./kibanaa.sh'])
f = open("C:/KibanaReports/myfile.sh", "a")
f.write(str5)
f.close()
time.sleep(3)
b = sp.call(['sh', 'C:/KibanaReports/./myfile.sh'])
b1 = "C:\\KibanaReports\\myfile.sh"
os.remove(a1)
os.remove(b1)
